### ISSUE TITLE
What format about send decode message to UDP server?

### ISSUE THREAD

**Issue by d9394** [jtdx-project/jtdx#1]
I have builded  a UDP server with python3, and I enabled sending logged ADIF QSO data in Primary UDP Server configure parameter in JDTX Setting, my UDP server receive message as below:

b'\xad\xbc\xcb\xda\x00\x00\x00\x02\x00\x00\x00\x00\x00\x00\x00\x10JTDX -  14074000\x00\x00\x00\x03\x00\x00\x00\x0b2.1.0-rc148'

 b'\xad\xbc\xcb\xda\x00\x00\x00\x02\x00\x00\x00\x01\x00\x00\x00\x10JTDX -  14074000\x00\x00\x00\x00\x00\xd6\xc0\x90\x00\x00\x00\x03FT8\x00\x00\x00\x00\x00\x00\x00\x03-15\x00\x00\x00\x03FT8\x00\x00\x00\x00\x00\n\xac\x00\x00\x05\xdc\x00\x00\x00\x06BG7JAW\x00\x00\x00\x04OL63\x00\x00\x00\x00\x00\xff\xff\xff\xff\x00\x00'

but I can't decode this message? what is wrong with me?

**Comment by jtdx-project** [comment]
Look udp protocol spec somewhere in WSJT-X site,
