### ISSUE TITLE
Send logged QSO ADIF data

### ISSUE THREAD

**Issue by R3KEE** [jtdx-project/jtdx#15]
Есть возможность добавить в передаваемые из JTDX по TCP, в сторонний лог ADIF данные, 2 поля?
<STATION_CALLSIGN:5>R3XXX
<MY_GRIDSQUARE:6>XX11XX
?
Is it possible to add 2 fields to the ADIF data transmitted from JTDX over TCP, to third-party software ? 
<STATION_CALLSIGN:5>XYXXX
<MY_GRIDSQUARE:6>XXYYXX
?

**Comment by jtdx-project** [comment]
Done in 158
