### ISSUE TITLE
Bug with Handling of TriggerCQ Message in JTDX 2.2.159

### ISSUE THREAD

**Issue by andy-hopkins** [jtdx-project/jtdx#23]
There seems to be a bug with the way a TriggerCQ message is handled in 2.2.159. 

According to NetworkMessage.hpp the message allows the caller to specify whether the CQ should be made on the odd or even time period by setting the "first" parameter.

MessageClient.cpp, lines 224 - 226 however ignore this parameter.. and instead causes the CQ to always be done on the odd period ...

                bool tx_period {false};
                bool send {true};
                in >> direction  >> send;

Line 226 should read 

in >> direction >> tx_period >> send;

I'd create a patch for this, or do something with github to fork & merge a change (if that the right terminology) but theres a way to go before I get that far :)

73
Andy, ZL1VAH

**Comment by jtdx-project** [comment]
added changes to code. TNX
