### ISSUE TITLE
Reporting QSO with Secondary UDP server bug

### ISSUE THREAD

**Issue by dontsnm** [jtdx-project/jtdx#3]
**Version:** JTDX v2.1.0-rc149 64-bit

**Issue:** Using the **Secondary UDP server** to send the Logged QSO to HRD or to Log4OM 2, it send the End Time as 00:00.00 (in the JTDX shows the right hour).  

**Notes:** If I use the same UDP server with WSJT-X, it log the QSO fine, with the right end hour.

**Comment by IgorChernikov** [comment]
fixed https://github.com/jtdx-project/jtdx/commit/184ca9771d6cf9b8648f5d196ed1ce7ff9ba5b70
patch will be in rc150 build

**Comment by mimo345** [comment]
At first glance...

 

rc 150

Everything's all set 

 

Checkbox for vertical bars on the Wide Graph O.K.!

very handy.

I work with Win 10 "lag" is almost always negative

and it's very good....

Congratulations to the developers, good results, perfect.

 

  73's Jean-Claude F1DSZ

 

****************************************

 

De : Igor Chernikov <notifications@github.com> 
Envoyé : jeudi 7 mai 2020 10:05
À : jtdx-project/jtdx <jtdx@noreply.github.com>
Cc : Subscribed <subscribed@noreply.github.com>
Objet : Re: [jtdx-project/jtdx] Reporting QSO with Secondary UDP server bug (#3)

 

fixed  <https://github.com/jtdx-project/jtdx/commit/184ca9771d6cf9b8648f5d196ed1ce7ff9ba5b70> 184ca97
patch will be in rc150 build
