### ISSUE TITLE
Flatpak build

### ISSUE THREAD

**Issue by LeandroStanger** [jtdx-project/jtdx#4]
Please, consider supporting [Flatpak](http://docs.flatpak.org/en/latest/introduction.html#reasons-to-use-flatpak) and publishing JTDX on [Flathub](https://github.com/flathub/flathub/wiki/App-Submission).

**Comment by jtdx-project** [comment]
JTDX is multiplatform software, Flatpak is Linux only. ( as there many distribution platforms for Linux ) We don't have time to support every distribution platform. If You like Flatpack, You are welcome to support it from github. We can publish packages in jtdx website.
