### ISSUE TITLE
Yaesu FT-991 tx forces USB mode

### ISSUE THREAD

**Issue by l3xis** [jtdx-project/jtdx#6]
Yaesu FT-991 connected over usb to PC.
Rig configured properly, "Test CAT" worked properly. "Test PTT" put transceiver in tx mode with selected on device mode (DATA-USB).
Then if i press "Tune" or "Enable Tx" button in main window, transceiver change mode to USB.

Can i change behavior to use device selected mode? Or select preffered mode in application?

**Comment by jtdx-project** [comment]
Are You sure that selecting Data/Pkt mode in radio tab still changes rig mode to USB??

**Comment by l3xis** [comment]
No. This is my mistake.

ср, 16 дек. 2020 г., 10:31 Arvo Järve <notifications@github.com>:

**Comment by jtdx-project** [comment]
resolved
